### Using Tensorflow like numpy

In [3]:
import tensorflow as tf

In [16]:
t = tf.constant([[1,2,3],[4,5,6]])

t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [17]:
tf.constant(45)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [18]:
t.shape

TensorShape([2, 3])

In [19]:
t.dtype

tf.int32

In [20]:
t[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [21]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [22]:
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [23]:
t[:,2,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [6]], dtype=int32)>

In [24]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [26]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [28]:
t@tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [30]:
tf.matmul(t,tf.transpose(t))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [31]:
import numpy as np

In [32]:
a = np.array([12,34,67])

In [33]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([12, 34, 67])>

In [34]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [35]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 144, 1156, 4489])>

In [36]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [37]:
 tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [39]:
tf.constant(2.) + tf.cast(tf.constant(40),tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [40]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])

In [41]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [43]:
v.assign(2+v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>