In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
housing = fetch_california_housing()

In [5]:
X_train_full,X_test,y_train_full,y_test = train_test_split(housing.data,housing.target)

In [6]:
X_train,X_valid,y_train,y_valid = train_test_split(X_train_full,y_train_full)

In [7]:
scaler = StandardScaler()

In [8]:
X_train_scaled = scaler.fit_transform(X_train)

In [9]:
X_valid_scaled = scaler.fit_transform(X_valid)
X_test_scaled = scaler.fit_transform(X_test)

In [10]:
from tensorflow import keras

### Batch Normalization with Keras

In [11]:
model = keras.models.Sequential([
 keras.layers.Flatten(input_shape=[28, 28]),
 keras.layers.BatchNormalization(),
 keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
 keras.layers.BatchNormalization(),
 keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
 keras.layers.BatchNormalization(),
 keras.layers.Dense(10, activation="softmax")
])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
batch_normalization (BatchNo (None, 784)               3136      
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
batch_normalization_1 (Batch (None, 300)               1200      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
batch_normalization_2 (Batch (None, 100)               400       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1

In [15]:
# Adding BN layers before activation function

In [16]:
model = keras.models.Sequential([
 keras.layers.Flatten(input_shape=[28, 28]),
 keras.layers.BatchNormalization(),
 keras.layers.Dense(300, kernel_initializer="he_normal", use_bias=False),
 keras.layers.BatchNormalization(),
 keras.layers.Activation("elu"),
 keras.layers.Dense(100, kernel_initializer="he_normal", use_bias=False),
 keras.layers.Activation("elu"),
 keras.layers.BatchNormalization(),
 keras.layers.Dense(10, activation="softmax")
])

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
batch_normalization_3 (Batch (None, 784)               3136      
_________________________________________________________________
dense_3 (Dense)              (None, 300)               235200    
_________________________________________________________________
batch_normalization_4 (Batch (None, 300)               1200      
_________________________________________________________________
activation (Activation)      (None, 300)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 100)               30000     
_________________________________________________________________
activation_1 (Activation)    (None, 100)              

## Gradient Clipping

In [18]:
optimizer = keras.optimizers.SGD(clipvalue=1.0)
model.compile(loss="mse", optimizer=optimizer)

## Optimizers

In [23]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

In [24]:
X_train_full.shape

(60000, 28, 28)

In [25]:
X_valid,X_train = X_train_full[:5000]/255.0,X_train_full[5000:]/255.0

In [26]:
y_valid,y_train = y_train_full[:5000], y_train_full[5000:]

In [27]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
 "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [28]:
class_names[y_train[0]]

'Coat'

In [30]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(300,activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(10,activation='softmax')
])

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
batch_normalization_9 (Batch (None, 784)               3136      
_________________________________________________________________
dense_9 (Dense)              (None, 300)               235500    
_________________________________________________________________
batch_normalization_10 (Batc (None, 300)               1200      
_________________________________________________________________
dense_10 (Dense)             (None, 100)               30100     
_________________________________________________________________
batch_normalization_11 (Batc (None, 100)               400       
_________________________________________________________________
dense_11 (Dense)             (None, 10)               

In [45]:
def optimizer_check(optimizer):
    model.compile(loss="sparse_categorical_crossentropy",optimizer=optimizer,metrics=["accuracy"])
    history = model.fit(X_train,y_train,epochs=20,validation_data=(X_valid,y_valid))
    X_new = X_test[:7]
    return np.argmax(model.predict(X_new),axis=1)

### Momentum Optimization

In [42]:
momentum_optimizer = keras.optimizers.SGD(lr=0.001, momentum=0.9)

In [46]:
mom = optimizer_check(momentum_optimizer)

Epoch 1/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1194 - accuracy: 0.9562 - val_loss: 0.3479 - val_accuracy: 0.8958
Epoch 2/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1147 - accuracy: 0.9588 - val_loss: 0.3403 - val_accuracy: 0.8998
Epoch 3/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1116 - accuracy: 0.9598 - val_loss: 0.3541 - val_accuracy: 0.8924
Epoch 4/20
1719/1719 [==============================] - 6s 3ms/step - loss: 0.1111 - accuracy: 0.9598 - val_loss: 0.3527 - val_accuracy: 0.8930
Epoch 5/20
1719/1719 [==============================] - 6s 3ms/step - loss: 0.1071 - accuracy: 0.9615 - val_loss: 0.3520 - val_accuracy: 0.8938
Epoch 6/20
1719/1719 [==============================] - 5s 3ms/step - loss: 0.1073 - accuracy: 0.9605 - val_loss: 0.3545 - val_accuracy: 0.8940
Epoch 7/20
1719/1719 [==============================] - 6s 3ms/step - loss: 0.1011 - accuracy: 0.9639 - val_loss: 0.3720 - val_accuracy:

In [50]:
y_test[:7]

array([9, 2, 1, 1, 6, 1, 4], dtype=uint8)

In [48]:
mom

array([9, 2, 1, 1, 6, 1, 4])

## RMS prop

In [47]:
rmsProp = keras.optimizers.RMSprop(lr=0.001, rho=0.9)

In [52]:
rms  = optimizer_check(rmsProp)

Epoch 1/20
1719/1719 [==============================] - 7s 4ms/step - loss: 0.2955 - accuracy: 0.8933 - val_loss: 0.3357 - val_accuracy: 0.8912
Epoch 2/20
1719/1719 [==============================] - 7s 4ms/step - loss: 0.2735 - accuracy: 0.8998 - val_loss: 0.3201 - val_accuracy: 0.8910
Epoch 3/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.2573 - accuracy: 0.9065 - val_loss: 0.3168 - val_accuracy: 0.8892
Epoch 4/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.2424 - accuracy: 0.9115 - val_loss: 0.3075 - val_accuracy: 0.8990
Epoch 5/20
1719/1719 [==============================] - 7s 4ms/step - loss: 0.2318 - accuracy: 0.9147 - val_loss: 0.3192 - val_accuracy: 0.8952
Epoch 6/20
1719/1719 [==============================] - 8s 5ms/step - loss: 0.2211 - accuracy: 0.9197 - val_loss: 0.3117 - val_accuracy: 0.8972
Epoch 7/20
1719/1719 [==============================] - 7s 4ms/step - loss: 0.2136 - accuracy: 0.9227 - val_loss: 0.3259 - val_accuracy:

In [53]:
rms

array([9, 2, 1, 1, 0, 1, 4])

In [54]:
y_test[:7]

array([9, 2, 1, 1, 6, 1, 4], dtype=uint8)

In [55]:
adam = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999)

In [56]:
ada = optimizer_check(adam)

Epoch 1/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1481 - accuracy: 0.9459 - val_loss: 0.3760 - val_accuracy: 0.8936
Epoch 2/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1378 - accuracy: 0.9488 - val_loss: 0.3678 - val_accuracy: 0.8996
Epoch 3/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1310 - accuracy: 0.9523 - val_loss: 0.3643 - val_accuracy: 0.8952
Epoch 4/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1313 - accuracy: 0.9514 - val_loss: 0.3700 - val_accuracy: 0.8982
Epoch 5/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1254 - accuracy: 0.9538 - val_loss: 0.3945 - val_accuracy: 0.9000
Epoch 6/20
1719/1719 [==============================] - 7s 4ms/step - loss: 0.1227 - accuracy: 0.9543 - val_loss: 0.3869 - val_accuracy: 0.8988
Epoch 7/20
1719/1719 [==============================] - 6s 4ms/step - loss: 0.1183 - accuracy: 0.9565 - val_loss: 0.3882 - val_accuracy:

In [57]:
ada

array([9, 2, 1, 1, 6, 1, 4])

In [58]:
y_test[:7]

array([9, 2, 1, 1, 6, 1, 4], dtype=uint8)